version: "3.9"

services:

  #Back-end Spring Boot Application
  spring:
    build: ./inventory
    container_name: spring
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine

  #Fron-end Angular Application
  angular:
    build: ./inventoryAng
    container_name: angular
    ports:
      - 4200:80
    links:
      - springboot-app