version: "3.9"

services:

  #Back-end Spring Boot Application
  springboot-app:
    build: ./inventory
    image: "spring-app"
    container_name: springboot-app
    ports:
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine

  #Fron-end Angular Application
  angular-app:
    build: ./inventoryAng
    image: "angular-app"
    container_name: angular-app
    ports:
      - 4200:80
    links:
      - springboot-app